<?php

namespace Database\Seeders;

use App\Models\Locations;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $locations = [
            [
                'location_category' => 1,
                'location_name' => 'Atlantica Langit Road #37',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_category' => 1,
                'location_name' => 'Pkg 8 J&T Langit Road #60',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_category' => 1,
                'location_name' => 'Lacson #36',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_category' => 1,
                'location_name' => 'Gym Langit Road #35',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_category' => 1,
                'location_name' => 'Atlantica Aklan Wire # 38',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_category' => 1,
                'location_name' => 'Treasurer Nest #40',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_category' => 2,
                'location_name' => 'Pkg 1 Kadiwa Market #75',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_category' => 2,
                'location_name' => 'Pkg 5 Buko King #18',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_category' => 1,
                'location_name' => 'Damayan Crossing #41',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_category' => 3,
                'location_name' => 'Senior High School Back Area',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_category' => 5,
                'location_name' => 'Health Center Philrads pkg 7B #2',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_category' => 1,
                'location_name' => 'Arko ph 9 exit #20',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_category' => 1,
                'location_name' => 'Pkg 6 & pkg 5 road #32',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_category' => 1,
                'location_name' => 'Crasher court pkg 5 #32',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_category' => 2,
                'location_name' => 'Maharlika 1 Jayoma #52',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_category' => 5,
                'location_name' => 'Philrads Health Center pkg 7b #1',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_category' => 5,
                'location_name' => 'BFP & Annex pkg 5 #34',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_category' => 1,
                'location_name' => 'Sampalukan Dulo pkg 1 #76',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_category' => 3,
                'location_name' => 'Genesis School pkg 5 #31',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_category' => 2,
                'location_name' => 'Maharlika Dulo Video #51',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('locations')->insert($locations);
    }
}