<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $locations = [
            [
                'location_name' => 'Atlantica Langit Road #37',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.779891404616476,
                'longitude' => 121.0382300966786,
                'description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Pkg 8 J&T Langit Road #60',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.779392577235317,
                'longitude' => 121.03925075575941,
                'description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Lacson #36',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => 'wala pang coordinates',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Gym Langit Road #35',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => 'wala pang coordinates',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Atlantica Aklan Wire # 38',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.780688552066275,
                'longitude' => 121.03921875017174,
                'description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Treasurer Nest #40',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => 'wala pang coordinates',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Pkg 1 Kadiwa Market #75',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => 'wala pang coordinates',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Pkg 5 Buko King #18',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => 'wala pang coordinates',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Damayan Crossing #41',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.782812248539633,
                'longitude' => 121.03961195187198,
                'description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Senior High School Back Area',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => 'wala pang coordinates',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Health Center Philrads pkg 7B #2',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.777615573362453,
                'longitude' => 121.03631418402236,
                'description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Arko ph 9 exit #20',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => 'wala pang coordinates',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Pkg 6 & pkg 5 road #32',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => 'wala pang coordinates',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Crasher court pkg 5 #32',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => 'wala pang coordinates',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Maharlika 1 Jayoma #52',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => 'wala pang coordinates',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Philrads Health Center pkg 7b #1',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.777615573362453,
                'longitude' => 121.03631418402236,
                'description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'BFP & Annex pkg 5 #34',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.781270313157409,
                'longitude' => 121.03715807961161,
                'description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Sampalukan Dulo pkg 1 #76',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => 'wala pang coordinates',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Genesis School pkg 5 #31',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.78125326313561,
                'longitude' => 121.03672820076504,
                'description' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'location_name' => 'Maharlika Dulo Video #51',
                'landmark' => '',
                'barangay' => 'Brgy. 176-E',
                'latitude' => 14.7647,
                'longitude' => 121.0533,
                'description' => 'wala pang coordinates',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('locations')->insert($locations);
    }
}
